#!/usr/bin/env bash
# The script loops from 1 to 10 end;
# display bad luck for the 4th loop
# display good luck for the 8th loop
# display Best School for the other

iterator=1

while (( iterator <= 10 ))
do
    if [ "$iterator" -eq "4" ]
    then
        echo "bad luck"
    elif [ "$iterator" -eq "8" ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi

    iterator=$(( iterator + 1 ))
done
